version: "3"
services:
  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - 27017:27017
    networks:
      synchronicity:
    volumes:
      - ./dev-conf/mongo-data:/data/db

  redis:
    image: redis:3.2.8-alpine
    networks:
      synchronicity:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3333:3306
    volumes:
      - ./dev-conf/mysql-data:/var/lib/mysql
    networks:
      synchronicity:
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=RSS

  charging:
    image: digicatsynch/charging7:latest
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
      - apis
      - rss
    ports:
      - 8006:8006
    networks:
      synchronicity:
        aliases:
          - charging.docker
    volumes:
      - ./dev-conf/charging-bills:/business-ecosystem-charging-backend/src/media/bills
      - ./dev-conf/charging-assets:/business-ecosystem-charging-backend/src/media/assets
      - ./dev-conf/charging-plugins:/business-ecosystem-charging-backend/src/plugins
      - ./dev-conf/charging-settings:/business-ecosystem-charging-backend/src/user_settings
    environment:
      - PAYPAL_CLIENT_ID=client_id_here
      - PAYPAL_CLIENT_SECRET=client_secret_here

  proxy:
    build: .
    restart: always
    ports:
      - "8004:8004"
    networks:
      synchronicity:
        aliases:
          - proxy.docker
    environment:
      - NODE_ENV=development

      - HOST=proxy.docker
      - PORT=8004
      - PROXY_HOST=proxy.docker
      - EXT_PORT=8004

      - OAUTH2_SERVER=http://idm.docker:3000
      - OAUTH2_CLIENT_ID=eff50ed2-df09-4d95-b704-cf87e550049c
      - OAUTH2_CLIENT_SECRET=16eb167a-7414-4140-aa6e-d1661ccfee2b
      - OAUTH2_CALLBACK_URL=http://proxy.docker:8004/auth/fiware/callback

      - MONGO_HOST=mongo

      - ENDPOINT_CHARGING_HOST=charging.docker
      - ENDPOINT_RSS_HOST=rss.docker

      - ENDPOINT_CATALOG_HOST=apis.docker
      - ENDPOINT_ORDERING_HOST=apis.docker
      - ENDPOINT_INVENTORY_HOST=apis.docker
      - ENDPOINT_PARTY_HOST=apis.docker
      - ENDPOINT_BILLING_HOST=apis.docker
      - ENDPOINT_CUSTOMER_HOST=apis.docker
      - ENDPOINT_USAGE_HOST=apis.docker

  apis:
    image: digicatsynch/bae-apis-synchronicity:sla2
    restart: always
    ports:
      - 4848:4848
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      synchronicity:
        aliases:
          - apis.docker
    volumes:
      - ./dev-conf/apis-conf:/etc/default/tmf/
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_HOST=mysql

  rss:
    image: conwetlab/biz-ecosystem-rss:v6.4.0
    restart: always
    ports:
      - 9999:8080
      - 4444:4848
      - 1111:8181
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      synchronicity:
        aliases:
          - rss.docker
    volumes:
      - ./dev-conf/rss-conf:/etc/default/rss

networks:
  synchronicity:
    external: true
