version: '3'
services:
    mongo:
        image: mongo:3.2
        ports:
            - 27017
        networks:
            main:
        volumes:
            - ./proxy-data:/data/db

    mysql:
        image: mysql:5.7
        restart: always
        expose:
            - 3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            main:
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=RSS

    apis:
        image: digicatsynch/bae-apis-synchronicity:v6.4.0
        ports:
            - 4848
            - 8080
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            main:
                aliases:
                    - apis.docker
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_HOST=mysql

    proxy:
        build: .
        links:
            - mongo
        depends_on:
            - mongo
            - apis
        ports:
            - 8004:8004
        networks:
            main:
                aliases:
                    - proxy.docker
        volumes:
            - ./proxy-indexes:/business-ecosystem-logic-proxy/indexes
            - ./proxy-themes:/business-ecosystem-logic-proxy/themes
            - ./proxy-static:/business-ecosystem-logic-proxy/static
            - ./proxy-locales:/business-ecosystem-logic-proxy/locales
        environment:
            - NODE_ENV=development
            - VERSION=6.3.0-rc
            - HOST=proxy.docker
            - PORT=8004

            - PROXY_ENABLED=true
            - PROXT_HOST=proxy.docker
            - PROXY_PORT=8004

            - EXT_PORT=8004
            - SSL_ENABLED=false

            - OAUTH2_SERVER=http://localhost:3000
            - OAUTH2_CLIENT_ID=eff50ed2-df09-4d95-b704-cf87e550049c
            - OAUTH2_CLIENT_SECRET=16eb167a-7414-4140-aa6e-d1661ccfee2b
            - OAUTH2_CALLBACK_URL=http://localhost:8004/auth/fiware/callback

            - MONGO_HOST=mongo

            - ENDPOINT_CATALOG_HOST=apis.docker
            - ENDPOINT_ORDERING_HOST=apis.docker
            - ENDPOINT_INVENTORY_HOST=apis.docker
            - ENDPOINT_PARTY_HOST=apis.docker
            - ENDPOINT_BILLING_HOST=apis.docker
            - ENDPOINT_CUSTOMER_HOST=apis.docker
            - ENDPOINT_USAGE_HOST=apis.docker

networks:
    main:
        external: true
