version: "3"
services:
  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - 27017:27017
    networks:
      synchronicity:
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:3.2.8-alpine
    networks:
      synchronicity:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3333:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      synchronicity:
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=RSS

  charging:
    image: digicatsynch/charging7:latest
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
      - apis
      - rss
    ports:
      - 8006:8006
    networks:
      synchronicity:
        aliases:
          - charging.docker
    volumes:
      - ./charging-bills:/business-ecosystem-charging-backend/src/media/bills
      - ./charging-assets:/business-ecosystem-charging-backend/src/media/assets
      - ./charging-plugins:/business-ecosystem-charging-backend/src/plugins
      - ./charging-settings:/business-ecosystem-charging-backend/src/user_settings
    environment:
      - PAYPAL_CLIENT_ID=client_id_here
      - PAYPAL_CLIENT_SECRET=client_secret_here

  apis:
    image: digicatsynch/bae-apis-synchronicity:sla2
    restart: always
    ports:
      - 4848:4848
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      synchronicity:
        aliases:
          - apis.docker
    volumes:
      - ./apis-conf:/etc/default/tmf/
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_HOST=mysql

  rss:
    image: conwetlab/biz-ecosystem-rss:v6.4.0
    restart: always
    ports:
      - 9999:8080
      - 4444:4848
      - 1111:8181
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      synchronicity:
        aliases:
          - rss.docker
    volumes:
      - ./rss-conf:/etc/default/rss

networks:
  synchronicity:
    external: true
