version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.17.0
    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Copy config file
          command: cp config.js.template config.js

      - run:
          name: Lint javascript files
          command: npm run lint

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  docker-ci-build:
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Login to docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build the docker image
          command: |
            docker build -t logicproxy7 .

      - run:
          name: Tag the docker image
          command: |
            docker tag logicproxy7 digicatsynch/logicproxy7:$CIRCLE_SHA1
            docker tag logicproxy7 digicatsynch/logicproxy7:ci-$CIRCLE_BUILD_NUM
            docker tag logicproxy7 digicatsynch/logicproxy7:${CIRCLE_BRANCH##feature/}

      - run:
          name: Push the docker image
          command: |
            docker push digicatsynch/logicproxy7:$CIRCLE_SHA1
            docker push digicatsynch/logicproxy7:ci-$CIRCLE_BUILD_NUM
            docker push digicatsynch/logicproxy7:${CIRCLE_BRANCH##feature/}

workflows:
  version: 2
  logic-proxy:
    jobs:
      - test
      - docker-ci-build:
          requires:
            - test
