version: '3'
services:
    mongo:
        image: mongo:3.2
        ports:
            - 27017
        volumes:
            - ./proxy-data:/data/db

    proxy:
        image: biz-ecosystem-logic-proxy
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8000
        volumes:
            - ./proxy-indexes:/business-ecosystem-logic-proxy/indexes
            - ./proxy-themes:/business-ecosystem-logic-proxy/themes
            - ./proxy-static:/business-ecosystem-logic-proxy/static
            - ./proxy-locales:/business-ecosystem-logic-proxy/locales
        environment:
            - NODE_ENV=development
            - MONGO_HOST=mongo
